name: Build and update Doxygen documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
        
    - name: Build Doxygen documentation
      uses: mattnotmitt/doxygen-action@v1.9
      with:
        doxyfile-path: "./Doxyfile" # default is ./Doxyfile
        working-directory: "." # default is .

    - name: Setup git config
      if: github.repository_owner == 'noisymime'
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "<>"

    - name: Commit updated Doxygen documentation
      if: github.event_name != 'pull_request' && github.repository_owner == 'noisymime'
      env:
        GH_DOXYGEN: ${{ secrets.GH_DOXYGEN }}
      run: |
        cd ..
        git clone https://github.com/speeduino/speeduino-doxygen
        cp -r speeduino/reference/doxygen/html/* speeduino-doxygen
        cd speeduino-doxygen
        git add --all
        git commit --allow-empty -m "Deploy code docs to GitHub repo. Commit ${GITHUB_SHA}"
        git push --force "https://${GH_DOXYGEN}@github.com/speeduino/speeduino-doxygen" > /dev/null 2>&1
