name: Validate INI

on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate INI
        uses: hyper-tuner/ini-validate-action@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          filename: reference/speeduino.ini
